// Generated by LiveScript 1.2.0
(function(){
  var expect, core, utils;
  expect = require('chai').expect;
  core = require('../../index');
  utils = core.util.utils;
  describe('util', function(){
    return describe('utils', function(){
      return describe('arrayIndexOf', function(){
        return specify('works', function(){
          return expect(1).to.eql(1);
        });
      });
    });
  });
}).call(this);
