// Generated by LiveScript 1.2.0
(function(){
  var core, patternLexer, expect, signalProducer;
  core = require('../../index');
  patternLexer = core.signal.Signals;
  expect = require('chai').expect;
  signalProducer = {};
  describe('signal', function(){
    return describe('Signals', function(){});
  });
}).call(this);
